# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    # নিচের লাইন টি বন্ধ করতে হবে কারণ এটা testing করার জন্য
    # - run: npm test

    # কারণ, পুশ করার পর pm2 restart করতে হয় তার জন্য project ফোল্ডার এ গিয়ে build করতে হবে এজন্য আমাদের সেখানে যেতে হবে আগে তাই বোঝার জন্য এটা লিখেছি পরের লাইনে আমরা Directory পরিবর্তন করতে আমদের Project ফোল্ডার এ যেতে চাই যেখানে package.json আছে। 
    - name: Change Directory 
      run: cd /home/client/vpn.swdrana/_work/vpn.swdrana/vpn.swdrana/
     
    # কারণ rafi নামে App টির ID: 0  এখানে আমার মনে হয় নাম লিখলেও হবে যেমনঃ - run: pm2 restart rafi
    - run: pm2 restart vpn.swdrana
